### ISSUE TITLE
Try installation on Linux 

### ISSUE THREAD

**Issue by MattiaPugliatti** [MattiaPugliatti/corto#20]

**Comment by PeterCalifano** [comment]
Hello there,

fyi I can confirm that the tutorial scripts for Didymos and Moon work as expected in Linux, specifically in Ubuntu 24.04 with python 3.11.10 and all module requirements pip automatically installs. I tried both following the installation instructions as you wrote in the README and installing the module manually (both cases in a virtual-env).

Just a couple of very minor things you may want to change:
1. The OBJ files for S05_Didymos downloaded from Drive have the extension in capital letters (.OBJ) which must be manually modified for the tutorial script to run.
![image](https://github.com/user-attachments/assets/e68cda95-e905-4291-9c02-e2482df074cc)

2. The tutorial script S05_Didymos expects a material filename that does not match with the file in the scenario folder and must be manually changed.
![image](https://github.com/user-attachments/assets/f901625c-f1d2-4e05-8845-7af146e1438a)
![image](https://github.com/user-attachments/assets/1352ac3f-829e-478f-9346-0a0e65abef6f)

3. An error is thrown by numpy at import time, possibly related to my case only. Anyhow it appears to be handled and not to cause troubles in using cortopy. Error message here:
```
(.venvCortopy) peterc@peterc-recoil:~/devDir/rendering-sw/corto_PeterCdev$  cd /home/peterc/devDir/rendering-sw/corto_PeterCdev ; /usr/bin/env /home/peterc/devDir/rendering-sw/corto_PeterCdev/.venvCortopy/bin/python /home/peterc/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 44283 -- /home/peterc/devDir/rendering-sw/corto_PeterCdev/tutorials/S05_Didymos.py 

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/peterc/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/home/peterc/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/home/peterc/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/peterc/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/home/peterc/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/home/peterc/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/home/peterc/devDir/rendering-sw/corto_PeterCdev/tutorials/S05_Didymos.py", line 12, in <module>
    import cortopy as corto
  File "/home/peterc/devDir/rendering-sw/corto_PeterCdev/cortopy/__init__.py", line 28, in <module>
    from ._Camera import Camera
  File "/home/peterc/devDir/rendering-sw/corto_PeterCdev/cortopy/_Camera.py", line 5, in <module>
    import bpy
AttributeError: _ARRAY_API not found
Unable to initialise audio
ImportError: numpy.core.multiarray failed to import 
```
4. In general, I modify the entry in .gitignore: .venv/ to a more convenient (for me) .venv*/
